sudo: required
language: generic
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
    CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud components update
  - gcloud version
  - gcloud compute ssh --quiet --project charged-formula-262616 --zone us-west1-b	 instance-1
  - docker pull gcr.io/charged-formula-262616/web-nginx
  # - eval $(ssh-agent -s)
  # - chmod 600 deploy_key_open
  # - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # - ssh-add deploy_key_open
  # - gcloud auth configure-docker
  # - sudo docker pull gcr.io/charged-formula-262616/web-client
  # - sudo docker pull gcr.io/charged-formula-262616/web-nginx
# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   on:
#     branch: master
