sudo: required
language: generic
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SERVER_IP_ADDRESS=104.196.226.118

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  # - curl https://sdk.cloud.google.com | bash > /dev/null;
  # - source $HOME/google-cloud-sdk/path.bash.inc
  # - gcloud components update
  # - gcloud auth activate-service-account --key-file service-account.json
  # - gcloud version
  # - gcloud auth configure-docker
  # # - gcloud compute ssh --project charged-formula-262616 --zone us-west1-b	 instance-1 --command="gcloud auth list"
  - eval $(ssh-agent -s)
  - sudo chmod 600 deploy_key_open
  - echo $?
  - ls -la
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add deploy_key_open
  - ssh-add -l
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
