version: "3"
services:
  client:
    restart: always
    image: gcr.io/charged-formula-262616/web-client
    ports:
      - 3000:3000
    volumes:
      - /app
    depends_on:
      - api
    links:
      - api

  api:
    image: gcr.io/charged-formula-262616/web-server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - /app
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD

  postgres:
    image: postgres
    ports:
      - "27017:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    restart: unless-stopped

  nginx:
    restart: always
    image: gcr.io/charged-formula-262616/web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/www/certbot/data:/usr/share/nginx/html/letsencrypt
      - ./var/www/certbot/conf:/etc/nginx/ssl
      - ./var/www/certbot/conf/dhparam:/etc/nginx/dhparam
    depends_on:
      - client
      - api
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./var/www/certbot/data:/usr/share/nginx/html/letsencrypt
      - ./var/www/certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --dry-run --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email azourelli+mywebsite@gmail.com --agree-tos --no-eff-email --force-renew -d andreszourelli.me -d www.andreszourelli.me
