version: "3"
services:
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
    links:
      - api

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env

  postgres:
    image: postgres
    ports:
      - "27017:5432"
    env_file:
      - ./server/.env

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
