version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  client:
    container_name: my-website
    restart: always
    build: ./client
    ports:
      - 3000:3000
    environment:
      VIRTUAL_HOST: http://192.168.99.100/client

  server:
    container_name: my-server
    build: ./server
    restart: always
    ports:
      - 5000:5000
    command: yarn start
    env_file:
      - ./server/.env
    environment:
      VIRTUAL_HOST: backend/0.0.0.0

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: nginx-proxy
