version: "3"
services:
  client:
    restart: always
    image: gcr.io/charged-formula-262616/web-client
    ports:
      - 3000:3000
    volumes:
      - /app
    depends_on:
      - api
    links:
      - api

  api:
    image: gcr.io/charged-formula-262616/web-server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - /app
    env_file:
      - ./.env
    links:
      - postgres

  postgres:
    image: postgres
    ports:
      - "27017:5432"
    env_file:
      - ./.env
    volumes:
      - ./var/database_projects/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf

  nginx:
    restart: always
    image: gcr.io/charged-formula-262616/web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-root:/var/www/html
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
      - ./logs:/var/log/nginx/
    depends_on:
      - client
      - api
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email azourelli+mywebsite@gmail.com --agree-tos --no-eff-email --force-renew -d andreszourelli.me -d www.andreszourelli.me
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/travis
      o: bind

networks:
  app-network:
    driver: bridge
