version: "3"
services:
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
    links:
      - api
    stdin_open: true
    environment:
      - "DANGEROUSLY_DISABLE_HOST_CHECK=true"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./server/.env

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
