version: "3"
services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  client:
    container_name: my-website
    restart: always
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - "./client:/srv/app/admin-client"
      - "/srv/app/admin-client/node_modules"
    depends_on:
      - api
    links:
      - api

  api:
    container_name: my-server
    build: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    command: yarn start
    env_file:
      - ./server/.env

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "27017:27017"
    env_file:
      - ./server/.env

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
# networks:
#   default:
#     external:
#       name: nginx-proxy

